#!/bin/bash

HEIGHT=80
WIDTH=40
CHOICE_HEIGHT=60

#/home/todd/bluez_five/bluetoothctl/forFLIGHT/bluetoothctlRECORD/tireSIZE.ods
# Create the menu and capture the user's selection

CHOICE=$(dialog --clear \
                --backtitle "My Script" \
                --title "Menu Dialog" \
                --menu "Select an tiew:" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                1  '12x1.75' \
                2  '12x1.95' \
                3  '14x1.50' \
                4  '14x1.75' \
                5  '16x1.50' \
                6  '16x1.75' \
                7  '16x2.00' \
                8  '16x1-1/8' \
                9  '16x1-3/8' \
                10  '17x1-1/4 (369)' \
                11  '18x1.50' \
                12  '18x1.75' \
                13  '20x1.25' \
                14  '20x1.35' \
                15  '20x1.50' \
                16  '20x1.75' \
                17  '20x1-1/8' \
                18  '20x1.95' \
                19  '20x1-3/8' \
                20  '24x1(520)' \
                21  '22x1-3/8' \
                22  '22x1-1/2' \
                23  '24x3/4 Tubular' \
                24  '24x1-1/8' \
                25  '24x1.75' \
                26  '24x1-1/4' \
                27  '26x1(559)' \
                28  '650C Tubular 26x7/8' \
                29  '24x2.00' \
                30  '650x20C' \
                31  '650x23C' \
                32  '26x1.25' \
                33  '650x25C 26x1(571)' \
                34  '24x2.125' \
                35  '26x1-1/8' \
                36  '26x1.40' \
                37  '26x1.50' \
                38  '26x1.75' \
                39  '26x1.95' \
                40  '26x2.10' \
                41  '26x1-3/8' \
                42  '26x2.125' \
                43  '2700x18C' \
                44  '27.5x1.50' \
                45  '2700x19C' \
                46  '26x2.35' \
                47  '2700x20C' \
                48  '27.5x1.95' \
                49  '**700x23C**' \
                50  '26x1-1/2' \
                51  '650x38B' \
                52  '2700x25C' \
                53  '650x38A' \
                54  '700C Tubular' \
                55  '2700x28C' \
                56  '27x1(630)' \
                57  '2700x30C' \
                58  '27.5x2.1' \
                59  '27x1-1/8' \
                60  '2700x32C' \
                61  '27x1-1/4' \
                62  '700x35C' \
                63  '27x1-3/8' \
                64  '26x3.00' \
                65  '700x38C' \
                66  '27.5x2.25' \
                67  '700x40C' \
                68  '700x42C' \
                69  '700x44C' \
                70  '700x45C' \
                71  '700x47C' \
                72  '29x2.1' \
                73  '29x2.2' \
                74  '29x2.3' \
                2>&1 >/dev/tty)

## clear

# Clear the dialog box and move the cursor back to the prompt
# to prevent the dialog box from being displayed on the terminal
clear

# Use a case statement to perform an action based on the choice
case $CHOICE in
     1)
        ./write_tire_size_to_speed_parameter '935'
        ;;
    2)
        ./write_tire_size_to_speed_parameter '940'
        ;;
    3)
        ./write_tire_size_to_speed_parameter '1020'
        ;;
    4)
        ./write_tire_size_to_speed_parameter '1055'
        ;;
    5)
        ./write_tire_size_to_speed_parameter '1185'
        ;;
    6)
        ./write_tire_size_to_speed_parameter '1195'
        ;;
    7)
        ./write_tire_size_to_speed_parameter '1245'
        ;;
    8)
        ./write_tire_size_to_speed_parameter '1290'
        ;;
    9)
        ./write_tire_size_to_speed_parameter '1300'
        ;;
    10)
        ./write_tire_size_to_speed_parameter '1340'
        ;;
    11)
        ./write_tire_size_to_speed_parameter '1340'
        ;;
    12)
        ./write_tire_size_to_speed_parameter '1350'
        ;;
    13)
        ./write_tire_size_to_speed_parameter '1450'
        ;;
    14)
        ./write_tire_size_to_speed_parameter '1460'
        ;;
    15)
        ./write_tire_size_to_speed_parameter '1490'
        ;;
    16)
        ./write_tire_size_to_speed_parameter '1515'
        ;;
    17)
        ./write_tire_size_to_speed_parameter '1545'
        ;;
    18)
        ./write_tire_size_to_speed_parameter '1565'
        ;;
    19)
        ./write_tire_size_to_speed_parameter '1615'
        ;;
    20)
        ./write_tire_size_to_speed_parameter '1753'
        ;;
    21)
        ./write_tire_size_to_speed_parameter '1770'
        ;;
    22)
        ./write_tire_size_to_speed_parameter '1785'
        ;;
    23)
        ./write_tire_size_to_speed_parameter '1785'
        ;;
    24)
        ./write_tire_size_to_speed_parameter '1795'
        ;;
    25)
        ./write_tire_size_to_speed_parameter '1890'
        ;;
    26)
        ./write_tire_size_to_speed_parameter '1905'
        ;;
    27)
        ./write_tire_size_to_speed_parameter '1913'
        ;;
    28)
        ./write_tire_size_to_speed_parameter '1920'
        ;;
    29)
        ./write_tire_size_to_speed_parameter '1925'
        ;;
    30)
        ./write_tire_size_to_speed_parameter '1938'
        ;;
    31)
        ./write_tire_size_to_speed_parameter '1944'
        ;;
    32)
        ./write_tire_size_to_speed_parameter '1950'
        ;;
    33)
        ./write_tire_size_to_speed_parameter '1952'
        ;;
    34)
        ./write_tire_size_to_speed_parameter '1965'
        ;;
    35)
        ./write_tire_size_to_speed_parameter '1970'
        ;;
    36)
        ./write_tire_size_to_speed_parameter '2005'
        ;;
    37)
        ./write_tire_size_to_speed_parameter '2010'
        ;;
    38)
        ./write_tire_size_to_speed_parameter '2023'
        ;;
    39)
        ./write_tire_size_to_speed_parameter '2050'
        ;;
    40)
        ./write_tire_size_to_speed_parameter '2068'
        ;;
    41)
        ./write_tire_size_to_speed_parameter '2068'
        ;;
    42)
        ./write_tire_size_to_speed_parameter '2070'
        ;;
    43)
        ./write_tire_size_to_speed_parameter '2070'
        ;;
    44)
        ./write_tire_size_to_speed_parameter '2079'
        ;;
    45)
        ./write_tire_size_to_speed_parameter '2080'
        ;;
    46)
        ./write_tire_size_to_speed_parameter '2083'
        ;;
    47)
        ./write_tire_size_to_speed_parameter '2086'
        ;;
    48)
        ./write_tire_size_to_speed_parameter '2090'
        ;;
    49)
        ./write_tire_size_to_speed_parameter '2096'
        ;;
    50)
        ./write_tire_size_to_speed_parameter '2100'
        ;;
    51)
        ./write_tire_size_to_speed_parameter '2105'
        ;;
    52)
        ./write_tire_size_to_speed_parameter '2105'
        ;;
    53)
        ./write_tire_size_to_speed_parameter '2125'
        ;;
    54)
        ./write_tire_size_to_speed_parameter '2130'
        ;;
    55)
        ./write_tire_size_to_speed_parameter '2136'
        ;;
    56)
        ./write_tire_size_to_speed_parameter '2145'
        ;;
    57)
        ./write_tire_size_to_speed_parameter '2146'
        ;;
    58)
        ./write_tire_size_to_speed_parameter '2148'
        ;;
    59)
        ./write_tire_size_to_speed_parameter '2155'
        ;;
    60)
        ./write_tire_size_to_speed_parameter '2155'
        ;;
    61)
        ./write_tire_size_to_speed_parameter '2161'
        ;;
    62)
        ./write_tire_size_to_speed_parameter '2168'
        ;;
    63)
        ./write_tire_size_to_speed_parameter '2169'
        ;;
    64)
        ./write_tire_size_to_speed_parameter '2170'
        ;;
    65)
        ./write_tire_size_to_speed_parameter '2180'
        ;;
    66)
        ./write_tire_size_to_speed_parameter '2182'
        ;;
    67)
        ./write_tire_size_to_speed_parameter '2200'
        ;;
    68)
        ./write_tire_size_to_speed_parameter '2224'
        ;;
    69)
        ./write_tire_size_to_speed_parameter '2235'
        ;;
    70)
        ./write_tire_size_to_speed_parameter '2242'
        ;;
    71)
        ./write_tire_size_to_speed_parameter '2268'
        ;;
    72)
        ./write_tire_size_to_speed_parameter '2288'
        ;;
    73)
        ./write_tire_size_to_speed_parameter '2298'
        ;;
    74)
        ./write_tire_size_to_speed_parameter '2326'
        ;;
esac
